class CreateInvestmentAdvisorFirms < ActiveRecord::Migration
  def change
    create_table :investment_advisor_firms do |t|
      t.integer :crd_number
      t.string  :sec_number
      t.string  :name
      t.string  :legal_name
      t.integer :main_office_loc_id
      t.string  :current_status
      t.date    :status_eff_date
      t.date    :last_adv_filing_date
      t.string  :url
      t.boolean :assets_gt_1b
      t.boolean :sec_reg_large_advisory_firm
      t.boolean :sec_reg_mid_advisory_firm
      t.boolean :sec_reg_main_office_in_wy
      t.boolean :sec_reg_main_office_outside_us
      t.boolean :sec_reg_adviser_to_investment_co
      t.boolean :sec_reg_adviser_to_biz_dev_co
      t.boolean :sec_reg_pension_consultant
      t.boolean :sec_reg_newly_formed
      t.boolean :sec_reg_multi_state
      t.boolean :sec_reg_internet_adviser
      t.boolean :sec_reg_no_longer_sec_eligible
      t.string  :organization
      t.string  :organization_other
      t.string  :org_state
      t.string  :org_country
      t.integer :num_employees
      t.integer :num_advisers
      t.integer :num_broker_dealer_reps
      t.integer :num_iars
      t.integer :num_iars_for_other_company
      t.integer :num_insurance_agents
      t.integer :num_solicit_clients
      t.string  :num_clients
      t.integer :num_clients_more_than_100
      t.integer :percent_clients_non_us
      t.string  :percent_clients_individuals
      t.string  :percent_clients_high_net_worth_individuals
      t.string  :percent_clients_banking_or_thrifts
      t.string  :percent_clients_investment_comps
      t.string  :percent_clients_biz_dev_comps
      t.string  :percent_clients_pooled_invest_vehicles
      t.string  :percent_clients_pension_plans
      t.string  :percent_clients_charities
      t.string  :percent_clients_non_listed_comps
      t.string  :percent_clients_state_or_muni_govs
      t.string  :percent_clients_other_invest_advisers
      t.string  :percent_clients_other_insurance_comps
      t.string  :percent_clients_other
      t.boolean  :comp_percent_assets
      t.boolean  :comp_hourly_rate
      t.boolean  :comp_sub_fee
      t.boolean  :comp_fixed_fee
      t.boolean  :comp_commission
      t.boolean  :comp_perf_fee
      t.string  :comp_other
      t.boolean :manage_portfolios
      t.integer :amount_under_management_desc
      t.integer :accounts_under_management_desc
      t.integer :amount_under_management_non_desc
      t.integer :accounts_under_management_non_desc
      t.integer :amount_under_management_total
      t.integer :accounts_under_management_total
      t.boolean :service_financial_planning
      t.boolean :service_ind_portfolio_management
      t.boolean :service_inv_comp_portfolio_management
      t.boolean :service_pooled_inv_portfolio_management
      t.boolean :service_inst_client_portfolio_management
      t.boolean :service_pension_consulting
      t.boolean :service_select_advisers
      t.boolean :service_publication
      t.boolean :service_security_rating
      t.boolean :service_market_timing
      t.boolean :service_education
      t.string :service_other
      t.string :service_ind_portfolio_management_num_clients
      t.boolean :activity_broker_dealer
      t.boolean :activity_reg_rep_broker_dealer
      t.boolean :activity_commodity_trading
      t.boolean :activity_futures_commission
      t.boolean :activity_real_estate
      t.boolean :activity_insurance
      t.boolean :activity_bank
      t.boolean :activity_trust
      t.boolean :activity_muni_adviser
      t.boolean :activity_security_swap_dealer
      t.boolean :activity_security_swap_participant
      t.boolean :activity_accountant
      t.boolean :activity_law
      t.string :activity_other
      t.boolean :custody_cash
      t.boolean :custody_securities
      t.integer :custody_total_amount
      t.integer :custody_total_clients
      t.boolean :custody_qualified_custodian
      t.boolean :custody_independent_audit
      t.boolean :custody_independent_examination
      t.boolean :custody_independent_control_report
      t.boolean :disc_felony_conviction
      t.boolean :disc_felony_charges
      t.boolean :disc_investment_misdemeanor_conviction
      t.boolean :disc_investment_misdemeanor_charges
      t.boolean :disc_sec_false_statement
      t.boolean :disc_sec_reg_violation
      t.boolean :disc_sec_cause_investment_auth_revoke
      t.boolean :disc_sec_investment_order
      t.boolean :disc_sec_civil_penalty
      t.boolean :disc_fed_false_statement
      t.boolean :disc_fed_reg_violation
      t.boolean :disc_fed_cause_investment_auth_revoke
      t.boolean :disc_fed_investment_order
      t.boolean :disc_fed_civil_penalty
      t.boolean :disc_org_false_statement
      t.boolean :disc_org_reg_violation
      t.boolean :disc_org_cause_investment_auth_revoke
      t.boolean :disc_org_investment_order
      t.boolean :disc_revoked_authority
      t.boolean :disc_current_proceedings
      t.boolean :disc_court_enjoined
      t.boolean :disc_court_reg_violations
      t.boolean :disc_court_civil_penalty
      t.boolean :disc_court_proceedings
      t.timestamps
    end
  end
end
